### ISSUE TITLE
Position bug.

### ISSUE THREAD

**Issue by DrZeit** [AndroFlo/SectionedRecyclerViewAdapter#2]
Hi, there is bug. When I click to "Pigeon" toast print, a "Albatros".

EDIT:

Sit down, simple fix: http://pastebin.com/vFSTfFzt

**Comment by DroidVent** [comment]
Hi, i am unable to make section with following response. Please help me.
"Dtae": "09/14/2015",
        "messages": [
          {
            "messageId": 26,
            "from": 12,
            "to": 1,
            "message": "ggggsggd",
            "timeAgo": "2015-09-14T15:00:49.000Z"
          },
          {
            "messageId": 41,
            "from": 12,
            "to": 1,
            "message": "hy",
            "timeAgo": "2015-09-15T14:23:49.000Z"
          }
]

**Comment by AndroFlo** [comment]
Hi DrZeit,
You can use 
```Java
mSectionedAdapter.getIndexForPosition(position);
```
 to get the good item selected
